language: python
python:
  - 3.4
install:
  - python bootstrap.py -c buildout.dev.cfg
  - bin/buildout -c buildout.dev.cfg
  - bin/bower update
script:
  - bin/wct --plugin wct-sauce --sauce-username=$SAUCE_USERNAME \
            --sauce-access-key=$SAUCE_ACCESS_KEY -s default
